- name: adding Ansible user to the Servers
  user:
    name: ansible
    groups: root
 
- name: adding ssh key for ansible user
  tags: always
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM+9OCKG3SkPXIfJauQd3BSsK930KYI3OaXPuCTC6WgT Ansible NoPP"

- name: adding ansible to sudoers file
  tags: always
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
