---

- hosts: all
  become: true
  tasks:

  - name: updating repository index for apt
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: installing apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: updating repository index for yum
    yum:
      update_cache: yes
    when: ansible_distribution in ["RedHat", "Amazon"]
#    when: ansible_distribution == "RedHat"
#    when: ansible_distribution == "RedHat" and ansible_distribution_version == "8.3"
  - name: installing httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution in ["RedHat","Amazon"]


