---

- hosts: all
  become: true
  tasks:

  - name: removing apache2 and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: removing httpd and php packages for Linux
    yum:
      name:
        - httpd
        - php
      state: absent
      update_cache: yes
    when: ansible_distribution in ["RedHat","Amazon"]


#    when: ansible_distribution == "RedHat" and ansible_distribution_version == "8.3"
#    when: ansible_distribution == "RedHat"
