---

- hosts: all
  become: true
  pre_tasks:

  - name: Updating resources (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Updating resources (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["RedHat", "Amazon"]


- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
