---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Installing updates for (APT) moduels
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Installing updates for (YUM) modules
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["RedHat", "Amazon"]

- hosts: web_servers
  become: true
  tasks:

  - name: installing apache2 package for Ubuntu Servers
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: installing httpd package for CentOS Servers
    yum:
      name: httpd
      state: latest
    when: ansible_distribution in ["RedHat","Amazon"]

- hosts: db_servers
  become: true
  tasks:

  - name: Installing mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
  
  - name: Installing mariadb package (CentOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution in ["RedHat", "Amazon"]

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    package:
      name: samba
      state: latest
